export const REGISTER_REQUEST = 'REGISTER_REQUEST';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';

export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';

export const LOGIN_TWO_STEP_REQUEST = 'LOGIN_TWO_STEP_REQUEST';
export const LOGIN_TWO_STEP_SUCCESS = 'LOGIN_TWO_STEP_SUCCESS';
export const LOGIN_TWO_STEP_FAILURE = 'LOGIN_TWO_STEP_FAILURE';

export const GET_USER_REQUEST = 'GET_USER_REQUEST';
export const GET_USER_SUCCESS = 'GET_USER_SUCCESS';
export const GET_USER_FAILURE = 'GET_USER_FAILURE';

// export const SEND_VERIFICATION_OTP_REQUEST = 'SEND_VERIFICATION_OTP_REQUEST';
// export const SEND_VERIFICATION_OTP_SUCCESS = 'SEND_VERIFICATION_OTP_SUCCESS';
// export const SEND_VERIFICATION_OTP_FAILURE = 'SEND_VERIFICATION_OTP_FAILURE';

// export const VERIFY_OTP_REQUEST = 'VERIFY_OTP_REQUEST';
// export const VERIFY_OTP_SUCCESS = 'VERIFY_OTP_SUCCESS';
// export const VERIFY_OTP_FAILURE = 'VERIFY_OTP_FAILURE';

// export const ENABLE_TWO_STEP_AUTHENTICATION_REQUEST = 'ENABLE_TWO_STEP_AUTHENTICATION_REQUEST';
// export const ENABLE_TWO_STEP_AUTHENTICATION_SUCCESS = 'ENABLE_TWO_STEP_AUTHENTICATION_SUCCESS';
// export const ENABLE_TWO_STEP_AUTHENTICATION_FAILURE = 'ENABLE_TWO_STEP_AUTHENTICATION_FAILURE';

// export const SEND_RESET_PASSWORD_REQUEST = 'SEND_RESET_PASSWORD_REQUEST';
// export const SEND_RESET_PASSWORD_SUCCESS = 'SEND_RESET_PASSWORD_SUCCESS';
// export const SEND_RESET_PASSWORD_FAILURE = 'SEND_RESET_PASSWORD_FAILURE';

// export const VERIFY_RESET_PASSWORD_REQUEST = 'VERIFY_RESET_PASSWORD_REQUEST';
// export const VERIFY_RESET_PASSWORD_SUCCESS = 'VERIFY_RESET_PASSWORD_SUCCESS';
// export const VERIFY_RESET_PASSWORD_FAILURE = 'VERIFY_RESET_PASSWORD_FAILURE';

// Two Factor Authentication Constants
export const SEND_TWO_FACTOR_OTP_REQUEST = 'SEND_TWO_FACTOR_OTP_REQUEST';
export const SEND_TWO_FACTOR_OTP_SUCCESS = 'SEND_TWO_FACTOR_OTP_SUCCESS';
export const SEND_TWO_FACTOR_OTP_FAILURE = 'SEND_TWO_FACTOR_OTP_FAILURE';

export const VERIFY_TWO_FACTOR_OTP_REQUEST = 'VERIFY_TWO_FACTOR_OTP_REQUEST';
export const VERIFY_TWO_FACTOR_OTP_SUCCESS = 'VERIFY_TWO_FACTOR_OTP_SUCCESS';
export const VERIFY_TWO_FACTOR_OTP_FAILURE = 'VERIFY_TWO_FACTOR_OTP_FAILURE';

export const UPDATE_USER_PROFILE = 'UPDATE_USER_PROFILE';

// Login 2FA Constants
export const LOGIN_2FA_REQUIRED = 'LOGIN_2FA_REQUIRED';
export const VERIFY_LOGIN_2FA_REQUEST = 'VERIFY_LOGIN_2FA_REQUEST';
export const VERIFY_LOGIN_2FA_SUCCESS = 'VERIFY_LOGIN_2FA_SUCCESS';
export const VERIFY_LOGIN_2FA_FAILURE = 'VERIFY_LOGIN_2FA_FAILURE';

// Account Verification Constants
export const SEND_ACCOUNT_VERIFICATION_OTP_REQUEST = 'SEND_ACCOUNT_VERIFICATION_OTP_REQUEST';
export const SEND_ACCOUNT_VERIFICATION_OTP_SUCCESS = 'SEND_ACCOUNT_VERIFICATION_OTP_SUCCESS';
export const SEND_ACCOUNT_VERIFICATION_OTP_FAILURE = 'SEND_ACCOUNT_VERIFICATION_OTP_FAILURE';

export const VERIFY_ACCOUNT_OTP_REQUEST = 'VERIFY_ACCOUNT_OTP_REQUEST';
export const VERIFY_ACCOUNT_OTP_SUCCESS = 'VERIFY_ACCOUNT_OTP_SUCCESS';
export const VERIFY_ACCOUNT_OTP_FAILURE = 'VERIFY_ACCOUNT_OTP_FAILURE';


export const DISABLE_TWO_FACTOR_OTP_REQUEST = 'DISABLE_TWO_FACTOR_OTP_REQUEST';
export const DISABLE_TWO_FACTOR_OTP_SUCCESS = 'DISABLE_TWO_FACTOR_OTP_SUCCESS';
export const DISABLE_TWO_FACTOR_OTP_FAILURE = 'DISABLE_TWO_FACTOR_OTP_FAILURE';

//Forgot Password Constants
export const SEND_FORGOT_PASSWORD_OTP_REQUEST = 'SEND_FORGOT_PASSWORD_OTP_REQUEST';
export const SEND_FORGOT_PASSWORD_OTP_SUCCESS = 'SEND_FORGOT_PASSWORD_OTP_SUCCESS';
export const SEND_FORGOT_PASSWORD_OTP_FAILURE = 'SEND_FORGOT_PASSWORD_OTP_FAILURE';

export const VERIFY_FORGOT_PASSWORD_OTP_REQUEST = 'VERIFY_FORGOT_PASSWORD_OTP_REQUEST';
export const VERIFY_FORGOT_PASSWORD_OTP_SUCCESS = 'VERIFY_FORGOT_PASSWORD_OTP_SUCCESS';
export const VERIFY_FORGOT_PASSWORD_OTP_FAILURE = 'VERIFY_FORGOT_PASSWORD_OTP_FAILURE';

export const RESET_PASSWORD_REQUEST = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';