export const GET_USER_WALLET_REQUEST = 'GET_USER_WALLET_REQUEST';
export const GET_USER_WALLET_SUCCESS = 'GET_USER_WALLET_SUCCESS';
export const GET_USER_WALLET_FAILURE = 'GET_USER_WALLET_FAILURE';

export const TRANSFER_MONEY_REQUEST = 'TRANSFER_MONEY_REQUEST';
export const TRANSFER_MONEY_SUCCESS = 'TRANSFER_MONEY_SUCCESS';
export const TRANSFER_MONEY_FAILURE = 'TRANSFER_MONEY_FAILURE';

export const GET_WALLET_TRANSACTIONS_REQUEST = 'GET_WALLET_TRANSACTIONS_REQUEST';
export const GET_WALLET_TRANSACTIONS_SUCCESS = 'GET_WALLET_TRANSACTIONS_SUCCESS';
export const GET_WALLET_TRANSACTIONS_FAILURE = 'GET_WALLET_TRANSACTIONS_FAILURE';

export const DEPOSIT_MONEY_REQUEST = 'DEPOSIT_MONEY_REQUEST';
export const DEPOSIT_MONEY_SUCCESS = 'DEPOSIT_MONEY_SUCCESS';
export const DEPOSIT_MONEY_FAILURE = 'DEPOSIT_MONEY_FAILURE';

export const CLEAR_TRANSFER_SUCCESS = 'CLEAR_TRANSFER_SUCCESS';
export const CLEAR_DEPOSIT_SUCCESS = 'CLEAR_DEPOSIT_SUCCESS';
export const CLEAR_WALLET_ERROR = 'CLEAR_WALLET_ERROR';
