export const WITHDRAWAL_REQUEST = 'WITHDRAWAL_REQUEST';
export const WITHDRAWAL_SUCCESS = 'WITHDRAWAL_SUCCESS';
export const WITHDRAWAL_FAILURE = 'WITHDRAWAL_FAILURE';
export const CLEAR_WITHDRAWAL_SUCCESS = 'CLEAR_WITHDRAWAL_SUCCESS';

export const WITHDRAWAL_PROCEED_REQUEST = 'WITHDRAWAL_PROCEED_REQUEST';
export const WITHDRAWAL_PROCEED_SUCCESS = 'WITHDRAWAL_PROCEED_SUCCESS';
export const WITHDRAWAL_PROCEED_FAILURE = 'WITHDRAWAL_PROCEED_FAILURE';

export const GET_WITHDRAWAL_HISTORY_REQUEST = 'GET_WITHDRAWAL_HISTORY_REQUEST';
export const GET_WITHDRAWAL_HISTORY_SUCCESS = 'GET_WITHDRAWAL_HISTORY_SUCCESS';
export const GET_WITHDRAWAL_HISTORY_FAILURE = 'GET_WITHDRAWAL_HISTORY_FAILURE';

export const GET_ALL_WITHDRAWALS_REQUEST = 'GET_ALL_WITHDRAWALS_REQUEST';
export const GET_ALL_WITHDRAWALS_SUCCESS = 'GET_ALL_WITHDRAWALS_SUCCESS';
export const GET_ALL_WITHDRAWALS_FAILURE = 'GET_ALL_WITHDRAWALS_FAILURE';


//the below are to add bank details and fetch bank details
export const ADD_PAYMENT_DETAILS_REQUEST = 'ADD_PAYMENT_DETAILS_REQUEST';
export const ADD_PAYMENT_DETAILS_SUCCESS = 'ADD_PAYMENT_DETAILS_SUCCESS';
export const ADD_PAYMENT_DETAILS_FAILURE = 'ADD_PAYMENT_DETAILS_FAILURE';

export const GET_PAYMENT_DETAILS_REQUEST = 'GET_PAYMENT_DETAILS_REQUEST';
export const GET_PAYMENT_DETAILS_SUCCESS = 'GET_PAYMENT_DETAILS_SUCCESS';
export const GET_PAYMENT_DETAILS_FAILURE = 'GET_PAYMENT_DETAILS_FAILURE';
